### ISSUE TITLE
github.com/mholt/caddy: github.com/mholt/caddy@v1.0.4: parsing go.mod:

### ISSUE THREAD

**Issue by liang-hiwin** [gravwell/coredns#1]
`root@debian:/# pushd $GOPATH/src/github.com/coredns/coredns/
~/go/src/github.com/coredns/coredns /
root@debian:~/go/src/github.com/coredns/coredns# sed -i 's/metadata:metadata/metadata:metadata\ngravwell:github.com\/gravwell\/coredns/g' plugin.cfg
root@debian:~/go/src/github.com/coredns/coredns# go generate
go: finding github.com/gravwell/coredns latest
go: github.com/coredns/coredns imports
        github.com/coredns/coredns/core/plugin imports
        github.com/gravwell/coredns imports
        github.com/mholt/caddy: github.com/mholt/caddy@v1.0.4: parsing go.mod:
        module declares its path as: github.com/caddyserver/caddy
                but was required as: github.com/mholt/caddy
`

**Comment by traetox** [comment]
We needed to roll over to go.mod and move some imports over to the new caddy import packages.

Commit b07db62c50226f6637cb34a1616f3b1616dae5a5 version 1.0.3 fixes this

you may need to run a `go get -u github.com/gravwell/coredns`

**Comment by liang-hiwin** [comment]
> 我们需要将鼠标移到go.mod上，并将一些导入内容移到新的caddy导入包中。
> 
> 提交[b07db62](https://github.com/gravwell/coredns/commit/b07db62c50226f6637cb34a1616f3b1616dae5a5)版本1.0.3修复了此问题
> 
> 您可能需要运行 `go get -u github.com/gravwell/coredns`

THANKS
