### ISSUE TITLE
Gravwell plugin should be non-blocking on connections

### ISSUE THREAD

**Issue by floren** [gravwell/coredns#2]
I am running coredns on my router, sending logs to a Gravwell container on the same box. Because it takes a bit for Docker containers to come up, the coredns gravwell plugin gives up when it can't connect to the indexers immediately. Make this non-blocking so I don't have to jam "ExecStartPre=/bin/sleep 30" in my service file!

**Comment by djfritz** [comment]
Fixed by #6 if you turn the cache on.
